# Generated by Django 2.1.7 on 2019-02-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='stateName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelbookingapp.State'),
        ),
    ]
