# Generated by Django 2.1.7 on 2019-02-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelbookingapp', '0003_hostel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
