# Generated by Django 2.1.7 on 2019-02-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelbookingapp', '0006_hostel_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='seet',
            new_name='seat',
        ),
    ]
