# Generated by Django 2.1.7 on 2019-02-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelbookingapp', '0012_auto_20190225_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Girls Hostel', 'Girls Hostel'), ('Boys Hostel', 'Boys Hostel')], max_length=20)),
                ('avaliable', models.CharField(choices=[('avaliable', 'avaliable'), ('unavaliable', 'unavaliable')], max_length=20)),
                ('images', models.FileField(upload_to='static/upload/hostel')),
                ('description', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('contact', models.CharField(default='90909', max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelbookingapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('roomImg', models.FileField(upload_to='static/upload/hostel')),
                ('avaliable', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelbookingapp.Hostel')),
            ],
        ),
    ]
