# Generated by Django 2.1.7 on 2019-02-26 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelbookingapp', '0015_hostel_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('fatherName', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=10)),
                ('tefin', models.CharField(choices=[('Interested', 'Interested'), ('NotInterested', 'NotInterested')], max_length=20)),
                ('photo', models.FileField(upload_to='static/upload/tenant')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelbookingapp.City')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelbookingapp.Room')),
            ],
        ),
    ]
