# Generated by Django 2.1.7 on 2019-02-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelbookingapp', '0016_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='photo',
            field=models.FileField(upload_to='upload/tenant'),
        ),
    ]
